// Supervisores por planta
const supervisores = {
  ALIMENTOS: "PINZON GUEVARA WILLIAM ORLANDO",
  ASEO: "OLGA LILIANA BERNAL RODRIGUEZ",
  GRANOS: "LEAL HERRERA JORGE ANDRES",
  BEBIDAS: "HENAO BEDOYA MARIA CRISTINA",
  OFERTAS: "HENAO BEDOYA MARIA CRISTINA",
  LOCATIVOS: "RICARDO ANDRES BEJARANO",
};


export { supervisores}